use serde::{Deserialize, Serialize};

/// Track metadata generated by AI (FAZA 2 Extended - B1-B11)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrackMetadataAI {
    pub genre: String,
    pub sub_genre: Option<String>,
    pub mood: String,
    pub energy_level: u8,      // 1-10
    pub tempo: String,         // slow, medium, fast
    pub danceability: u8,      // 1-10 (B7)
    pub vocal_type: String,    // instrumental, female vocals, male vocals, mixed vocals, rap, choir (B8)
    pub decade: String,        // 1960s, 1970s, 1980s, 1990s, 2000s, 2010s, 2020s (B9)
    pub language: String,      // English, Romanian, Spanish, French, Instrumental, etc. (B10)
    pub activity_tags: Vec<String>,  // workout, study, sleep, driving, party, cooking, meditation (B11)
    pub occasion_tags: Vec<String>,  // wedding, birthday, christmas, summer, road trip (B11)
    pub keywords: Vec<String>,
}

/// Smart playlist suggestion
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaylistSuggestion {
    pub name: String,
    pub description: String,
    pub search_queries: Vec<String>,
}

/// Parsed natural language command
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "command")]
pub enum PlayerCommand {
    #[serde(rename = "play")]
    Play { query: Option<String> },
    #[serde(rename = "pause")]
    Pause,
    #[serde(rename = "next")]
    Next,
    #[serde(rename = "previous")]
    Previous,
    #[serde(rename = "favorite")]
    AddToFavorites,
    #[serde(rename = "search")]
    Search { query: String },
    #[serde(rename = "create_playlist")]
    CreatePlaylist { name: String, description: Option<String> },
    #[serde(rename = "set_mood")]
    SetMood { mood: String },
    #[serde(rename = "set_volume")]
    SetVolume { level: f32 },
    #[serde(rename = "add_to_queue")]
    AddToQueue { query: String },
    #[serde(rename = "toggle_shuffle")]
    ToggleShuffle,
    #[serde(rename = "set_repeat")]
    SetRepeat { mode: String },
    #[serde(rename = "navigate")]
    Navigate { view: String },
    #[serde(rename = "download")]
    Download { query: Option<String> },
    #[serde(rename = "multi")]
    MultiCommand { commands: Vec<PlayerCommand> },
    #[serde(rename = "unknown")]
    Unknown,
}

/// Mood search response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MoodSearchResponse {
    pub queries: Vec<String>,
    pub explanation: String,
}

/// Activity search response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySearchResponse {
    pub queries: Vec<String>,
    pub recommended_bpm: String,
    pub energy_level: u8,
}

/// Era search response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EraSearchResponse {
    pub queries: Vec<String>,
    pub time_period: String,
    pub notable_artists: Vec<String>,
}

/// Similar artist info
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimilarArtist {
    pub name: String,
    pub similarity_reason: String,
    pub confidence: String,
}

/// Similar artists response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimilarArtistsResponse {
    pub similar_artists: Vec<SimilarArtist>,
    pub search_queries: Vec<String>,
}

/// Lyric search response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LyricSearchResponse {
    pub queries: Vec<String>,
    pub related_themes: Vec<String>,
}

/// Translation info
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Translation {
    pub language: String,
    pub query: String,
    pub cultural_variant: Option<String>,
}

/// Cross-language search response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrossLanguageSearchResponse {
    pub original_language: String,
    pub translations: Vec<Translation>,
    pub search_queries: Vec<String>,
}

/// Contextual suggestions response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextualSuggestionsResponse {
    pub detected_patterns: Vec<String>,
    pub suggested_mood: String,
    pub queries: Vec<String>,
    pub reasoning: String,
}

/// Autocomplete suggestion
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutocompleteSuggestion {
    pub text: String,
    #[serde(rename = "type")]
    pub suggestion_type: String,
    pub confidence: String,
}

/// Smart autocomplete response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SmartAutocompleteResponse {
    pub completions: Vec<AutocompleteSuggestion>,
}

/// Query interpretation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryInterpretation {
    pub meaning: String,
    pub confidence: String,
    pub queries: Vec<String>,
}

/// Vague query resolution response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VagueQueryResponse {
    pub interpretations: Vec<QueryInterpretation>,
    pub clarification_questions: Vec<String>,
    pub best_guess_queries: Vec<String>,
}

/// Smart Playlist Plan with filtering criteria (FAZA 3)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SmartPlaylistPlan {
    pub name: String,
    pub description: String,
    pub genres: Vec<String>,
    pub moods: Vec<String>,
    pub energy_min: u8,
    pub energy_max: u8,
    pub decades: Vec<String>,
    pub tempo: Option<String>,
    pub activities: Vec<String>,
    pub search_queries: Vec<String>,
}

/// Daily Mix plan response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailyMixPlan {
    pub name: String,
    pub description: String,
    pub track_ids: Vec<String>,
}

/// Prompt templates for various AI tasks
pub struct Prompts;

impl Prompts {
    /// Enhance a search query for better YouTube results
    pub fn enhance_search(user_query: &str, recent_genres: &[String]) -> String {
        let genres_context = if recent_genres.is_empty() {
            String::new()
        } else {
            format!(
                "\nGenurile recent ascultate de utilizator: {}",
                recent_genres.join(", ")
            )
        };

        format!(
            r#"Ești un asistent pentru căutare muzică pe YouTube.

Cererea utilizatorului: "{}"{}

Generează exact 3 căutări YouTube optimizate care să găsească muzica dorită.
Consideră:
- Termeni alternativi (ex: "rock românesc" -> "romanian rock music")
- Artiști sau piese specifice care se potrivesc descrierii
- Variante în engleză dacă originalul e în română

Returnează JSON:
{{
  "queries": ["query1", "query2", "query3"]
}}"#,
            user_query, genres_context
        )
    }

    /// Analyze a track for auto-tagging (FAZA 2 Extended - B1-B11 combined)
    /// Single mega-prompt for all metadata fields (more efficient than 11 separate calls)
    /// Temperature: 0.2 for consistency
    pub fn analyze_track(title: &str, artist: &str) -> String {
        format!(
            r#"Analizează această piesă muzicală și clasifică-o în detaliu:

**Titlu:** {}
**Artist:** {}

Returnează JSON cu EXACT această structură (toate câmpurile sunt obligatorii):
{{
  "genre": "genul principal (ex: rock, pop, electronic, jazz, classical, hip-hop, metal, folk, country, indie, R&B)",
  "sub_genre": "sub-genul sau null (ex: progressive rock, synthwave, melodic techno, nu metal, indie pop)",
  "mood": "starea de spirit dominantă (ex: energetic, melancholic, peaceful, aggressive, romantic, chill, uplifting, dark, dreamy)",
  "energy_level": număr între 1-10 (1=foarte calm/ambient, 5=moderat, 10=foarte energetic/intense),
  "tempo": "slow" | "medium" | "fast",
  "danceability": număr între 1-10 (1=neadecvat pentru dans, 5=moderat, 10=perfect pentru dans/club),
  "vocal_type": "instrumental" | "female vocals" | "male vocals" | "mixed vocals" | "rap" | "choir" | "spoken word",
  "decade": "1960s" | "1970s" | "1980s" | "1990s" | "2000s" | "2010s" | "2020s" (deceniul când a fost lansată sau stilul caracteristic),
  "language": "English" | "Romanian" | "Spanish" | "French" | "Italian" | "German" | "Instrumental" | "Other" (limba versurilor sau "Instrumental"),
  "activity_tags": ["max 4 tags din: workout, study, sleep, driving, party, cooking, meditation, gaming, running, yoga, focus, relaxation"],
  "occasion_tags": ["max 3 tags din: wedding, birthday, christmas, summer, winter, road trip, romantic dinner, festival, night out, morning routine"],
  "keywords": ["max 5 cuvinte cheie descriptive despre piesa (ex: guitar-driven, synth-heavy, acoustic, orchestral, bass-heavy)"]
}}

**EXEMPLE:**
- "Bohemian Rhapsody" by Queen → genre: "rock", sub_genre: "progressive rock", mood: "dramatic", energy_level: 7, tempo: "medium", danceability: 4, vocal_type: "male vocals", decade: "1970s", language: "English", activity_tags: ["driving", "singing along"], occasion_tags: ["road trip"], keywords: ["operatic", "multi-part", "iconic", "guitar solo"]

- "Weightless" by Marconi Union → genre: "ambient", sub_genre: "downtempo", mood: "peaceful", energy_level: 1, tempo: "slow", danceability: 1, vocal_type: "instrumental", decade: "2010s", language: "Instrumental", activity_tags: ["sleep", "meditation", "relaxation", "yoga"], occasion_tags: ["spa", "bedtime"], keywords: ["anxiety relief", "calming", "minimal", "atmospheric"]

- "Levels" by Avicii → genre: "electronic", sub_genre: "progressive house", mood: "uplifting", energy_level: 9, tempo: "fast", danceability: 10, vocal_type: "female vocals", decade: "2010s", language: "English", activity_tags: ["workout", "party", "running", "gaming"], occasion_tags: ["festival", "night out"], keywords: ["synth-driven", "energetic", "anthemic", "EDM"]

Returnează DOAR JSON, fără text suplimentar. Bazează-te pe cunoștințele tale despre artist și stilul lor muzical."#,
            title, artist
        )
    }

    /// Parse natural language player command
    pub fn parse_command(user_input: &str, available_views: &[&str]) -> String {
        let views = available_views.join(", ");
        format!(
            r#"Parsează comanda pentru un player de muzică. Înțelege limba română și engleză.

Input utilizator: "{}"

Comenzi disponibile:
- play: pornește redarea (opțional cu query de căutare)
- pause: pauză
- next: următoarea melodie
- previous: melodia anterioară
- favorite: adaugă la favorite
- search: caută muzică
- create_playlist: creează playlist nou (cu name și description opțional)
- set_mood: setează mood pentru recomandări
- set_volume: setează volumul (level: 0.0 - 1.0, ex: "50%" -> 0.5)
- add_to_queue: adaugă o melodie în coadă (cu query)
- toggle_shuffle: activează/dezactivează shuffle
- set_repeat: setează modul repeat (mode: "none", "one", "all")
- navigate: navighează la o secțiune (view: {})
- download: descarcă melodia curentă sau o melodie specificată
- multi: comenzi multiple (commands: array de comenzi)
- unknown: dacă nu se potrivește nimic

Returnează DOAR JSON valid, fără text suplimentar:
{{
  "command": "numele_comenzii",
  ... parametri specifici comenzii
}}

Exemple:
- "pune ceva rock" -> {{"command": "play", "query": "rock music"}}
- "pauză" -> {{"command": "pause"}}
- "caută Metallica" -> {{"command": "search", "query": "Metallica"}}
- "adaugă la favorite" -> {{"command": "favorite"}}
- "volum 70%" -> {{"command": "set_volume", "level": 0.7}}
- "adaugă Bohemian Rhapsody în coadă" -> {{"command": "add_to_queue", "query": "Bohemian Rhapsody"}}
- "amestecă" / "shuffle" -> {{"command": "toggle_shuffle"}}
- "repetă melodia" -> {{"command": "set_repeat", "mode": "one"}}
- "du-mă la setări" -> {{"command": "navigate", "view": "settings"}}
- "descarcă" -> {{"command": "download"}}
- "pune rock și dă volumul la maxim" -> {{"command": "multi", "commands": [{{"command": "play", "query": "rock"}}, {{"command": "set_volume", "level": 1.0}}]}}
- "open library" -> {{"command": "navigate", "view": "library"}}
- "play something chill and shuffle" -> {{"command": "multi", "commands": [{{"command": "play", "query": "chill music"}}, {{"command": "toggle_shuffle"}}]}}"#,
            user_input, views
        )
    }

    /// Generate smart playlist based on description
    pub fn generate_playlist(
        description: &str,
        duration_minutes: Option<u32>,
        existing_artists: &[String],
    ) -> String {
        let duration_context = duration_minutes
            .map(|d| format!("\nDurată dorită: aprox. {} minute", d))
            .unwrap_or_default();

        let artists_context = if existing_artists.is_empty() {
            String::new()
        } else {
            format!(
                "\nArtiști din biblioteca utilizatorului: {}",
                existing_artists.iter().take(10).cloned().collect::<Vec<_>>().join(", ")
            )
        };

        format!(
            r#"Creează un playlist bazat pe această descriere:

"{}"{}{}

Generează un playlist cu:
1. Un nume atractiv
2. O descriere scurtă
3. 5-10 căutări YouTube pentru a găsi piese potrivite

Returnează JSON:
{{
  "name": "numele playlistului",
  "description": "descriere scurtă",
  "search_queries": ["artist - song", "query2", ...]
}}"#,
            description, duration_context, artists_context
        )
    }

    /// Verify best YouTube match for Spotify track
    pub fn verify_spotify_match(
        spotify_title: &str,
        spotify_artist: &str,
        spotify_album: &str,
        spotify_duration_sec: Option<i64>,
        youtube_results: &[(String, String, String, Option<i64>)], // (id, title, channel, duration)
    ) -> String {
        let duration_info = spotify_duration_sec
            .map(|d| format!(" (durată: {}:{})", d / 60, d % 60))
            .unwrap_or_default();

        let results_text: String = youtube_results
            .iter()
            .enumerate()
            .map(|(i, (id, title, channel, dur))| {
                let dur_str = dur
                    .map(|d| format!(" [{}:{}]", d / 60, d % 60))
                    .unwrap_or_default();
                format!("{}. ID:{} - \"{}\" de {}{}", i + 1, id, title, channel, dur_str)
            })
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            r#"Selectează cel mai bun match YouTube pentru această piesă Spotify:

Track Spotify:
- Titlu: {}
- Artist: {}
- Album: {}{}

Rezultate YouTube:
{}

Criterii de selecție (în ordine descrescătoare de importanță):
1. Versiunea oficială (audio oficial, VEVO, canalul artistului)
2. Calitate audio (preferă "audio", "official audio" față de "video")
3. Durată similară (±15 secunde)
4. Evită: cover-uri, versiuni live (decât dacă nu există alternativă), remixuri

Returnează JSON:
{{
  "selected_id": "id-ul YouTube ales sau null dacă niciunul nu e potrivit",
  "confidence": "high" | "medium" | "low",
  "reason": "explicație scurtă"
}}"#,
            spotify_title, spotify_artist, spotify_album, duration_info, results_text
        )
    }

    /// Search music by mood
    pub fn mood_search(mood: &str, user_library_genres: &[String]) -> String {
        let library_context = if user_library_genres.is_empty() {
            String::new()
        } else {
            format!(
                "\nGenuri din biblioteca utilizatorului: {}",
                user_library_genres.join(", ")
            )
        };

        format!(
            r#"Generează căutări YouTube pentru muzică care se potrivește acestei stări de spirit:

Stare de spirit: "{}"{}

Consideră diferite genuri și artiști care exprimă această stare.
Generează 5 căutări diverse care acoperă:
- Genuri diferite (rock, electronic, jazz, classical, etc.)
- Intensități diferite ale stării respective
- Atât piese vocale cât și instrumentale

Returnează JSON:
{{
  "queries": ["query1", "query2", "query3", "query4", "query5"],
  "explanation": "scurtă explicație despre alegeri"
}}"#,
            mood, library_context
        )
    }

    /// Search music by activity
    pub fn activity_search(activity: &str, duration_minutes: Option<u32>) -> String {
        let duration_context = duration_minutes
            .map(|d| format!("\nDurată dorită: {} minute", d))
            .unwrap_or_default();

        format!(
            r#"Generează căutări YouTube pentru muzică potrivită acestei activități:

Activitate: "{}"{}

Consideră:
- BPM-ul și energia potrivită pentru activitate
- Dacă activitatea necesită concentrare sau motivație
- Muzică fără sau cu vocale (după caz)

Exemple activități și caracteristici:
- workout: energetic, 120-140 BPM, motivațional
- study/focus: calm, instrumental, fără distracții
- sleep/relaxation: foarte calm, ambient, liniștitor
- cooking: medium energy, vesel
- driving: rhythm constant, energizant moderat
- party: foarte energetic, dansabil

Returnează JSON:
{{
  "queries": ["query1", "query2", "query3", "query4", "query5"],
  "recommended_bpm": "intervalul BPM recomandat",
  "energy_level": număr 1-10
}}"#,
            activity, duration_context
        )
    }

    /// Search music by era/decade
    pub fn era_search(era: &str, genre_filter: Option<&str>) -> String {
        let genre_context = genre_filter
            .map(|g| format!("\nGen dorit: {}", g))
            .unwrap_or_default();

        format!(
            r#"Generează căutări YouTube pentru muzică din această eră:

Eră: "{}"{}

Interpretează cererea în mod flexibil:
- Decenii specifice: "70s", "80s", "90s", "2000s"
- Perioade: "modern", "retro", "vintage", "classic"
- Ere muzicale: "golden age hip hop", "grunge era", "disco era"

Generează 5 căutări care acoperă:
- Artiști și hituri emblematice din acea perioadă
- Diferite genuri populare în acea eră
- Atât mainstream cât și underground

Returnează JSON:
{{
  "queries": ["query1", "query2", "query3", "query4", "query5"],
  "time_period": "perioada identificată (ex: 1970-1979)",
  "notable_artists": ["artist1", "artist2", "artist3"]
}}"#,
            era, genre_context
        )
    }

    /// Find similar artists
    pub fn similar_artists(artist_name: &str, user_favorites: &[String]) -> String {
        let favorites_context = if user_favorites.is_empty() {
            String::new()
        } else {
            format!(
                "\nArtiști favoriți ai utilizatorului: {}",
                user_favorites.join(", ")
            )
        };

        format!(
            r#"Găsește artiști similari cu:

Artist: "{}"{}

Consideră:
- Stil muzical și genuri
- Perioada de activitate
- Influențe artistice
- Sound și producție similară

Generează 6-8 artiști similari, începând cu cei mai similari.
Dacă artistul apare în favoritele utilizatorului, ține cont de ei.

Returnează JSON:
{{
  "similar_artists": [
    {{"name": "Artist Name", "similarity_reason": "motiv scurt", "confidence": "high/medium/low"}}
  ],
  "search_queries": ["query pentru fiecare artist similar"]
}}"#,
            artist_name, favorites_context
        )
    }

    /// Search by lyric themes
    pub fn lyric_search(theme: &str) -> String {
        format!(
            r#"Generează căutări YouTube pentru piese cu versuri despre:

Temă: "{}"

Consideră:
- Piese cunoscute care abordează această temă
- Diferite genuri muzicale
- Atât abordări directe cât și metaforice ale temei
- Diferite limbi (engleză, română, etc.)

Generează 5 căutări diverse.

Returnează JSON:
{{
  "queries": ["query1", "query2", "query3", "query4", "query5"],
  "related_themes": ["temă similară1", "temă similară2"]
}}"#,
            theme
        )
    }

    /// Cross-language search with translation
    pub fn cross_language_search(query: &str, target_languages: &[String]) -> String {
        let languages_str = if target_languages.is_empty() {
            "engleză, română, spaniolă, franceză".to_string()
        } else {
            target_languages.join(", ")
        };

        format!(
            r#"Traducă și generează căutări în multiple limbi pentru:

Query original: "{}"
Limbi țintă: {}

Pași:
1. Identifică limba și intenția query-ului original
2. Traduce conceptul în limbile țintă
3. Generează căutări naturale în fiecare limbă
4. Include variante culturale (ex: "rock românesc" vs "romanian rock")

Returnează JSON:
{{
  "original_language": "limba detectată",
  "translations": [
    {{"language": "limba", "query": "query tradus", "cultural_variant": "variantă culturală dacă se aplică"}}
  ],
  "search_queries": ["toate căutările combinate"]
}}"#,
            query, languages_str
        )
    }

    /// Contextual suggestions based on listening history
    pub fn contextual_suggestions(
        recent_tracks: &[(String, String)], // (title, artist)
        time_of_day: &str,
        day_of_week: &str,
    ) -> String {
        let tracks_text: String = recent_tracks
            .iter()
            .take(10)
            .map(|(title, artist)| format!("- {} by {}", title, artist))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            r#"Generează sugestii contextuale bazate pe istoricul de ascultare:

Piese recente:
{}

Context actual:
- Ora: {}
- Zi: {}

Analizează:
1. Genurile și stările de spirit din istoricul recent
2. Contextul temporal (oră din zi, zi din săptămână)
3. Posibile pattern-uri (ex: muzică energică dimineața, calmă seara)

Generează 5 sugestii de căutare care:
- Se potrivesc pattern-ului observat
- Sunt apropiate de preferințele recente
- Consideră contextul temporal

Returnează JSON:
{{
  "detected_patterns": ["pattern1", "pattern2"],
  "suggested_mood": "starea sugerată",
  "queries": ["query1", "query2", "query3", "query4", "query5"],
  "reasoning": "explicație scurtă"
}}"#,
            tracks_text, time_of_day, day_of_week
        )
    }

    /// Smart autocomplete suggestions
    pub fn smart_autocomplete(partial_query: &str, popular_searches: &[String]) -> String {
        let popular_context = if popular_searches.is_empty() {
            String::new()
        } else {
            format!(
                "\nCăutări populare recente: {}",
                popular_searches.join(", ")
            )
        };

        format!(
            r#"Generează completări inteligente pentru această căutare parțială:

Input parțial: "{}"{}

Reguli:
1. Completări trebuie să înceapă cu textul introdus
2. Sugerează atât artiști cât și genuri/mood-uri
3. Include variante în română și engleză
4. Consideră greșeli de scriere comune

Generează 5-8 completări diversificate.

Returnează JSON:
{{
  "completions": [
    {{"text": "completare", "type": "artist/genre/mood/song", "confidence": "high/medium/low"}}
  ]
}}"#,
            partial_query, popular_context
        )
    }

    /// Resolve vague/ambiguous queries
    pub fn resolve_vague_query(vague_query: &str, context_tracks: &[(String, String)]) -> String {
        let context_text = if context_tracks.is_empty() {
            String::new()
        } else {
            let tracks: String = context_tracks
                .iter()
                .take(5)
                .map(|(title, artist)| format!("- {} by {}", title, artist))
                .collect::<Vec<_>>()
                .join("\n");
            format!("\nContext (piese recente):\n{}", tracks)
        };

        format!(
            r#"Interpretează și clarifică această cerere vagă/ambiguă:

Cerere: "{}"{}

Query-ul poate fi:
- Vag (ex: "ceva fain", "muzică bună", "ce-mi place")
- Ambiguu (ex: "rock", fără alte detalii)
- Incomplet (ex: "ca aia cu...", "gen...")
- Pronume/referințe (ex: "mai astea", "așa ceva")

Generează:
1. Interpretări posibile ale cererii
2. Întrebări de clarificare (dacă e necesar)
3. Căutări concrete bazat pe interpretarea cea mai probabilă

Returnează JSON:
{{
  "interpretations": [
    {{"meaning": "interpretare", "confidence": "high/medium/low", "queries": ["query1", "query2"]}}
  ],
  "clarification_questions": ["întrebare1", "întrebare2"],
  "best_guess_queries": ["query bazat pe interpretarea principală"]
}}"#,
            vague_query, context_text
        )
    }

    // ========================================================================
    // SMART PLAYLIST GENERATION (FAZA 3)
    // ========================================================================

    /// Generate a smart playlist plan from description, mood, or activity
    pub fn smart_playlist_plan(
        description: &str,
        method: &str,
        duration_minutes: Option<u32>,
        library_genres: &[String],
        library_moods: &[String],
    ) -> String {
        let duration_hint = duration_minutes
            .map(|d| format!("\nTarget duration: approximately {} minutes.", d))
            .unwrap_or_default();

        let library_context = if library_genres.is_empty() && library_moods.is_empty() {
            String::new()
        } else {
            format!(
                "\nUser's library contains these genres: [{}]\nUser's library contains these moods: [{}]",
                library_genres.join(", "),
                library_moods.join(", ")
            )
        };

        let method_instruction = match method {
            "mood" => format!(
                "The user wants a playlist matching this mood/feeling: \"{}\".\nFocus on mood-appropriate genres, tempos, and energy levels.",
                description
            ),
            "activity" => format!(
                "The user wants a playlist for this activity: \"{}\".\nChoose tempo, energy, and genre appropriate for the activity.",
                description
            ),
            _ => format!(
                "The user described their desired playlist as: \"{}\"",
                description
            ),
        };

        format!(
            r#"You are a music curator AI. Create a smart playlist plan.

{}{}{}

Generate a structured plan with:
1. A catchy playlist name
2. A short description (1-2 sentences)
3. Filtering criteria to match existing library tracks
4. 5-10 YouTube search queries to find additional tracks

IMPORTANT: For genres, moods, decades, activities - use lowercase values.
For energy_min and energy_max use 1-10 scale.
For tempo use: "slow", "medium", "fast", or null if any tempo is fine.

Return JSON:
{{
  "name": "Playlist Name",
  "description": "Short description",
  "genres": ["rock", "metal"],
  "moods": ["energetic", "aggressive"],
  "energy_min": 6,
  "energy_max": 10,
  "decades": ["1980s", "1990s"],
  "tempo": "fast",
  "activities": ["workout", "driving"],
  "search_queries": ["AC/DC Thunderstruck", "Metallica Enter Sandman", ...]
}}"#,
            method_instruction, duration_hint, library_context
        )
    }

    /// Generate a "more like this" playlist plan from a seed track
    pub fn seed_track_playlist(
        title: &str,
        artist: &str,
        genre: Option<&str>,
        mood: Option<&str>,
        energy: Option<i32>,
        decade: Option<&str>,
    ) -> String {
        let metadata_context = {
            let mut parts = Vec::new();
            if let Some(g) = genre { parts.push(format!("Genre: {}", g)); }
            if let Some(m) = mood { parts.push(format!("Mood: {}", m)); }
            if let Some(e) = energy { parts.push(format!("Energy: {}/10", e)); }
            if let Some(d) = decade { parts.push(format!("Decade: {}", d)); }
            if parts.is_empty() {
                String::new()
            } else {
                format!("\nKnown metadata: {}", parts.join(", "))
            }
        };

        format!(
            r#"You are a music curator AI. Create a "More Like This" playlist plan.

Seed track: "{}" by {}{}

Generate a playlist of similar tracks. Consider:
- Same or adjacent genres
- Similar mood and energy level
- Same era/decade or timeless classics
- Similar artists or musical style

Return JSON:
{{
  "name": "Playlist Name",
  "description": "Short description",
  "genres": ["genre1", "genre2"],
  "moods": ["mood1"],
  "energy_min": 5,
  "energy_max": 8,
  "decades": ["1980s", "1990s"],
  "tempo": null,
  "activities": [],
  "search_queries": ["Artist - Song", "Another Artist - Song", ...]
}}"#,
            title, artist, metadata_context
        )
    }

    // ========================================================================
    // PLAYLIST VARIANTS (FAZA 3 — C2-C4, C7-C12)
    // ========================================================================

    /// C2: Generate a mood-based playlist from library
    #[allow(dead_code)]
    pub fn mood_playlist(mood: &str, library_tracks: &str) -> String {
        format!(
            r#"You are a music curator AI. Create a playlist for the mood "{}".

Library tracks:
{}

Select and order tracks from the library that match this mood best.
Return JSON:
{{
  "name": "Playlist Name",
  "description": "Short mood-themed description",
  "track_ids": ["id1", "id2", ...],
  "vibe": "one-line vibe description"
}}"#,
            mood, library_tracks
        )
    }

    /// C3: Generate a duration-limited playlist
    #[allow(dead_code)]
    pub fn duration_playlist(duration_min: u32, theme: &str, library_tracks: &str) -> String {
        format!(
            r#"You are a music curator AI. Create a playlist of approximately {} minutes with the theme "{}".

Library tracks (with durations):
{}

Select tracks that fit the theme and total roughly {} minutes (allow ±10%).
Return JSON:
{{
  "name": "Playlist Name",
  "description": "Short description",
  "track_ids": ["id1", "id2", ...],
  "estimated_duration_min": 45
}}"#,
            duration_min, theme, library_tracks, duration_min
        )
    }

    /// C4: Generate a mood-transition playlist (e.g., energetic → calm)
    #[allow(dead_code)]
    pub fn transition_playlist(start_mood: &str, end_mood: &str, library_tracks: &str) -> String {
        format!(
            r#"You are a music curator AI. Create a playlist that transitions from "{}" to "{}".

Library tracks with metadata:
{}

Order tracks so the playlist starts with "{}" energy and gradually transitions to "{}" by the end. This is a journey playlist.
Return JSON:
{{
  "name": "Journey: {} → {}",
  "description": "A smooth transition from {} to {}",
  "track_ids": ["id1", "id2", ...],
  "transition_points": ["start: {}", "mid: transitional", "end: {}"]
}}"#,
            start_mood, end_mood, library_tracks,
            start_mood, end_mood,
            start_mood, end_mood, start_mood, end_mood,
            start_mood, end_mood
        )
    }

    /// C7: Discovery playlist — find hidden gems based on known preferences
    #[allow(dead_code)]
    pub fn discovery_playlist(known_artists: &str, preferred_genres: &str) -> String {
        format!(
            r#"You are a music discovery AI. Based on the user's taste, suggest NEW artists and tracks they haven't heard.

Known artists: {}
Preferred genres: {}

Suggest tracks by lesser-known or adjacent artists they likely haven't discovered yet.
Return JSON:
{{
  "name": "Discovery Mix",
  "description": "Undiscovered gems for your taste",
  "search_queries": ["Artist - Song", "Artist - Song", ...],
  "reasoning": "Why these match the user's taste"
}}"#,
            known_artists, preferred_genres
        )
    }

    /// C8: Generate a name for a playlist based on its tracks
    #[allow(dead_code)]
    pub fn name_playlist(track_list: &str) -> String {
        format!(
            r#"You are a creative playlist naming AI. Look at these tracks and create a catchy playlist name.

Tracks:
{}

Return JSON:
{{
  "names": ["Creative Name 1", "Creative Name 2", "Creative Name 3"],
  "best": "The Best Name",
  "reasoning": "Why this name fits"
}}"#,
            track_list
        )
    }

    /// C9: Describe a playlist cover / visual theme
    #[allow(dead_code)]
    pub fn describe_playlist_cover(track_list: &str) -> String {
        format!(
            r##"You are an art director AI. Describe a visual cover concept for this playlist.

Tracks:
{}

Return JSON:
{{
  "description": "Vivid visual description for the cover art",
  "color_palette": ["#hex1", "#hex2", "#hex3"],
  "mood_keywords": ["keyword1", "keyword2"],
  "style": "minimalist|abstract|photographic|illustrated"
}}"##,
            track_list
        )
    }

    /// C10: Smart reorder a playlist for optimal flow
    #[allow(dead_code)]
    pub fn reorder_playlist(tracks_with_metadata: &str) -> String {
        format!(
            r#"You are a DJ AI. Reorder these tracks for the best listening flow.

Current track order with metadata:
{}

Reorder considering: energy flow (build-up/cool-down arcs), key compatibility, genre transitions, tempo changes.
Return JSON:
{{
  "track_ids": ["id1", "id2", ...],
  "strategy": "Description of the ordering strategy used",
  "highlights": ["Track X → Track Y creates a great energy transition"]
}}"#,
            tracks_with_metadata
        )
    }

    /// C11: Merge two playlists intelligently
    #[allow(dead_code)]
    pub fn merge_playlists(playlist_a: &str, playlist_b: &str) -> String {
        format!(
            r#"You are a playlist curator AI. Merge these two playlists into one cohesive playlist.

Playlist A:
{}

Playlist B:
{}

Interleave tracks for a smooth listening experience. Remove duplicates. Create flow.
Return JSON:
{{
  "name": "Merged Playlist Name",
  "description": "How the merge was approached",
  "track_ids": ["id1", "id2", ...],
  "removed_duplicates": ["id1"]
}}"#,
            playlist_a, playlist_b
        )
    }

    /// C12: Split a large playlist into themed sub-playlists
    #[allow(dead_code)]
    pub fn split_playlist(tracks_with_metadata: &str) -> String {
        format!(
            r#"You are a playlist organizer AI. Split this large playlist into themed sub-playlists.

Tracks with metadata:
{}

Group tracks by mood, genre, energy, or theme into 2-5 coherent sub-playlists.
Return JSON:
{{
  "playlists": [
    {{
      "name": "Sub-playlist Name",
      "description": "Theme description",
      "track_ids": ["id1", "id2", ...]
    }}
  ],
  "reasoning": "How the split was decided"
}}"#,
            tracks_with_metadata
        )
    }

    // ========================================================================
    // DAILY MIX (FAZA 3 - Step 3.5)
    // ========================================================================

    /// C6: Generate a Daily Mix playlist based on listening history and time context
    pub fn daily_mix(
        library_summary: &str,
        recent_tracks: &str,
        hour: u32,
        day_of_week: &str,
        top_genres: &[String],
        top_moods: &[String],
    ) -> String {
        let time_context = match hour {
            5..=8 => "Early morning — gentle, calm music to start the day",
            9..=11 => "Morning — upbeat, productive energy",
            12..=13 => "Lunchtime — relaxed, moderate energy",
            14..=16 => "Afternoon — focused, steady energy",
            17..=19 => "Evening — transitioning from work, mixed energy",
            20..=22 => "Night — relaxed or social vibe",
            _ => "Late night — calm, ambient, winding down",
        };

        let weekend_hint = match day_of_week {
            "Saturday" | "Sunday" => "\nIt's the weekend — user might want relaxed or party vibes.",
            "Friday" => "\nIt's Friday — user might want upbeat/celebratory music.",
            _ => "",
        };

        let genres_context = if top_genres.is_empty() {
            "Not enough data yet".to_string()
        } else {
            top_genres.join(", ")
        };

        let moods_context = if top_moods.is_empty() {
            "Not enough data yet".to_string()
        } else {
            top_moods.join(", ")
        };

        format!(
            r#"You are a personal DJ AI creating a \"Daily Mix\" playlist.

Current context:
- Time: {}:00 ({})
- Day: {}{}
- User's top genres: {}
- User's top moods: {}

Recently played (for variety — avoid repeating these):
{}

Available library tracks (id | title | artist | genre | mood | energy):
{}

Create a personalized Daily Mix of 10-15 tracks that:
1. Matches the time-of-day context
2. Reflects the user's top genres and moods
3. Avoids recently played tracks
4. Starts with a strong opener that fits the vibe
5. Has good flow — energy transitions should be smooth
6. Mixes favorites with less-played tracks for discovery

Also generate a catchy name and description for today's mix.

Return JSON:
{{
  "name": "Daily Mix — descriptive theme",
  "description": "Short 1-sentence description of today's vibe",
  "track_ids": ["id1", "id2", ...]
}}"#,
            hour, time_context, day_of_week, weekend_hint,
            genres_context, moods_context, recent_tracks, library_summary
        )
    }

    // ========================================================================
    // SMART SPOTIFY IMPORT PROMPTS (FAZA 4 - D1-D5)
    // ========================================================================

    /// D2: Disambiguate track — when multiple YouTube results look similar
    pub fn disambiguate_track(
        title: &str,
        artist: &str,
        album: &str,
        results: &[(String, String, String, Option<i64>)], // (id, title, channel, duration)
    ) -> String {
        let results_text: String = results
            .iter()
            .enumerate()
            .map(|(i, (id, yt_title, channel, dur))| {
                let dur_str = dur
                    .map(|d| format!(" [{}:{:02}]", d / 60, d % 60))
                    .unwrap_or_default();
                format!("{}. ID:{} | \"{}\" | Canal: {}{}", i + 1, id, yt_title, channel, dur_str)
            })
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            r#"Ai de dezambiguizat rezultatele YouTube pentru o piesă Spotify.

Track Spotify:
- Titlu: "{}"
- Artist: "{}"
- Album: "{}"

Rezultate YouTube (toate par similare):
{}

Decide care rezultat este versiunea originală/oficială a piesei. Prioritizează:
1. Audio oficial / canalul oficial al artistului / VEVO
2. Versiunea de studio (nu live, nu cover, nu remix)
3. Calitate audio bună (preferă "official audio" vs "lyric video" vs "music video")
4. Durată corespunzătoare (versiunile de studio au durată standard)

Returnează JSON:
{{
  "selected_id": "id-ul YouTube ales",
  "confidence": "high" | "medium" | "low",
  "reason": "explicație scurtă de ce ai ales acest rezultat",
  "is_cover": false,
  "is_live": false,
  "is_remix": false
}}"#,
            title, artist, album, results_text
        )
    }

    /// D3: Alternative search queries when primary search fails
    pub fn alternative_queries(
        track_name: &str,
        artist_name: &str,
        album: &str,
    ) -> String {
        format!(
            r#"Piesa Spotify nu a fost găsită pe YouTube cu căutarea standard.

Track:
- Titlu: "{}"
- Artist: "{}"
- Album: "{}"

Generează 5 căutări alternative YouTube care ar putea găsi această piesă:
1. Variante ale numelui (cu/fără caractere speciale, prescurtări)
2. Căutare doar după artist + cuvinte cheie din titlu
3. Căutare cu "official audio" sau "lyrics"
4. Căutare cu numele albumului
5. Transliterare/traducere dacă titlul e în altă limbă

Returnează JSON:
{{
  "queries": ["query1", "query2", "query3", "query4", "query5"],
  "likely_issue": "explicație de ce căutarea standard a eșuat (ex: caractere speciale, titlu ambiguu, artist obscur)",
  "suggestion": "sugestie pentru utilizator dacă nimic nu funcționează"
}}"#,
            track_name, artist_name, album
        )
    }

    /// D4: Assess match quality between Spotify track and YouTube result
    pub fn assess_match_quality(
        spotify_title: &str,
        spotify_artist: &str,
        spotify_album: &str,
        spotify_duration_sec: Option<i64>,
        youtube_title: &str,
        youtube_channel: &str,
        youtube_duration_sec: Option<i64>,
    ) -> String {
        let sp_dur = spotify_duration_sec
            .map(|d| format!("{}:{:02}", d / 60, d % 60))
            .unwrap_or("necunoscut".to_string());
        let yt_dur = youtube_duration_sec
            .map(|d| format!("{}:{:02}", d / 60, d % 60))
            .unwrap_or("necunoscut".to_string());

        format!(
            r#"Evaluează calitatea match-ului dintre o piesă Spotify și un rezultat YouTube.

Piesă Spotify:
- Titlu: "{}"
- Artist: "{}"
- Album: "{}"
- Durată: {}

Rezultat YouTube:
- Titlu: "{}"
- Canal: "{}"
- Durată: {}

Analizează:
1. Titlul se potrivește? (atenție la variante, feat., remaster, etc.)
2. Artistul/canalul e corect? (VEVO, canal oficial, etc.)
3. Durația e similară? (diferență > 30s = suspect, > 60s = probabil greșit)
4. E versiunea de studio sau live/cover/remix?
5. E o compilație/mix în loc de piesă individuală?

Returnează JSON:
{{
  "quality": "high" | "medium" | "low" | "mismatch",
  "score": 85,
  "issues": ["problemă1", "problemă2"],
  "is_correct_track": true,
  "is_correct_artist": true,
  "is_studio_version": true,
  "duration_match": true,
  "recommendation": "accept" | "review" | "reject" | "re-search"
}}"#,
            spotify_title, spotify_artist, spotify_album, sp_dur,
            youtube_title, youtube_channel, yt_dur
        )
    }

    /// D5: Suggest similar/alternative track when original can't be found
    pub fn suggest_similar_track(
        track_name: &str,
        artist_name: &str,
        album: &str,
    ) -> String {
        format!(
            r#"O piesă Spotify nu a putut fi găsită pe YouTube. Sugerează alternative similare.

Piesa lipsă:
- Titlu: "{}"
- Artist: "{}"
- Album: "{}"

Generează:
1. Alte piese ale aceluiași artist care sunt similare ca stil
2. Piese similare de alți artiști
3. Căutări YouTube specifice pentru fiecare sugestie

Returnează JSON:
{{
  "same_artist_alternatives": [
    {{"title": "titlu", "reason": "de ce e similară"}}
  ],
  "other_artist_alternatives": [
    {{"title": "titlu", "artist": "artist", "reason": "de ce e similară"}}
  ],
  "search_queries": ["query1", "query2", "query3", "query4", "query5"]
}}"#,
            track_name, artist_name, album
        )
    }

    // ========================================================================
    // SMART QUEUE PROMPTS (FAZA 4 - I1-I6)
    // ========================================================================

    /// I1: Smart auto-play — pick next track(s) from library based on current track
    pub fn smart_queue_next(
        current_title: &str,
        current_artist: &str,
        current_genre: Option<&str>,
        current_mood: Option<&str>,
        current_energy: Option<i32>,
        recent_track_ids: &[String],
        library_summary: &str,
        count: usize,
    ) -> String {
        let current_meta = {
            let mut parts = Vec::new();
            if let Some(g) = current_genre { parts.push(format!("Genre: {}", g)); }
            if let Some(m) = current_mood { parts.push(format!("Mood: {}", m)); }
            if let Some(e) = current_energy { parts.push(format!("Energy: {}/10", e)); }
            if parts.is_empty() { "No metadata available".to_string() }
            else { parts.join(", ") }
        };

        let recently_played = if recent_track_ids.is_empty() {
            "None".to_string()
        } else {
            format!("IDs to EXCLUDE (recently played): {:?}", recent_track_ids)
        };

        format!(
            r#"You are a smart DJ AI. The user just finished listening to a track and needs the next track(s) to play.

Currently playing: "{}" by {}
Metadata: {}
{}

Available library tracks (id | title | artist | genre | mood | energy):
{}

Select the {} best next track(s) from the library. Consider:
- Musical flow: similar genre/mood but not identical (variety!)
- Energy continuity: don't jump abruptly from 9 to 2
- Avoid recently played tracks
- Mix familiar favorites with less-played tracks

Return ONLY a JSON array of track IDs in play order:
["track-id-1", "track-id-2", ...]"#,
            current_title, current_artist, current_meta, recently_played,
            library_summary, count
        )
    }

    /// I2: Crossfade suggestion — optimal crossfade duration between two tracks
    pub fn crossfade_suggestion(
        track_a_title: &str,
        track_a_genre: Option<&str>,
        track_a_energy: Option<i32>,
        track_a_tempo: Option<&str>,
        track_b_title: &str,
        track_b_genre: Option<&str>,
        track_b_energy: Option<i32>,
        track_b_tempo: Option<&str>,
    ) -> String {
        let meta_a = format!(
            "genre={}, energy={}, tempo={}",
            track_a_genre.unwrap_or("unknown"),
            track_a_energy.map(|e| e.to_string()).unwrap_or("?".into()),
            track_a_tempo.unwrap_or("unknown")
        );
        let meta_b = format!(
            "genre={}, energy={}, tempo={}",
            track_b_genre.unwrap_or("unknown"),
            track_b_energy.map(|e| e.to_string()).unwrap_or("?".into()),
            track_b_tempo.unwrap_or("unknown")
        );

        format!(
            r#"You are a DJ mixing expert. Suggest the optimal crossfade duration between two tracks.

Track A (ending): "{}" [{}]
Track B (starting): "{}" [{}]

Rules:
- Same genre + similar tempo → short crossfade (2-4s)
- Different genres → longer crossfade (5-8s)  
- High energy to low energy → gradual crossfade (6-10s)
- Electronic/ambient → longer crossfade (8-12s)
- Rock/metal with hard endings → short or no crossfade (0-2s)

Return ONLY JSON:
{{ "duration_seconds": 5, "reason": "brief explanation" }}"#,
            track_a_title, meta_a, track_b_title, meta_b
        )
    }

    /// I3: Wake-up sequence — morning energy ramp
    pub fn wake_up_sequence(
        library_summary: &str,
        duration_minutes: u32,
    ) -> String {
        format!(
            r#"You are a smart DJ creating a wake-up morning sequence.

Target duration: ~{} minutes
Goal: Start very calm/ambient (energy 1-3), gradually increase to energetic (energy 7-10)

Available library tracks (id | title | artist | genre | mood | energy):
{}

Create a sequence of tracks that:
1. Starts with the calmest, most ambient tracks
2. Gradually increases energy every 2-3 tracks
3. Ends with upbeat, energizing tracks
4. Total ~{} minutes (estimate ~3.5 min per track)

Return ONLY a JSON array of track IDs in wake-up order:
["calm-track-id", "medium-track-id", ..., "energetic-track-id"]

IMPORTANT: Do NOT include any reasoning, thoughts, explanation, or chain-of-thought. Output must start with [ and end with ]. Only JSON, nothing else."#,
            duration_minutes, library_summary, duration_minutes
        )
    }

    /// I4: Sleep timer sequence — wind-down energy decrease
    pub fn sleep_timer_sequence(
        library_summary: &str,
        duration_minutes: u32,
    ) -> String {
        format!(
            r#"You are a smart DJ creating a sleep/wind-down sequence.

Target duration: ~{} minutes
Goal: Start at current energy level, gradually decrease to very calm (energy 1-3)

Available library tracks (id | title | artist | genre | mood | energy):
{}

Create a sequence of tracks that:
1. Starts with current-energy tracks
2. Gradually decreases energy every 2-3 tracks
3. Ends with the calmest, most relaxing tracks
4. Prefer: slow tempo, instrumental, ambient, acoustic
5. Total ~{} minutes (estimate ~3.5 min per track)

Return ONLY a JSON array of track IDs in sleep order:
["current-energy-id", "calmer-id", ..., "very-calm-id"]

IMPORTANT: Do NOT include any reasoning, thoughts, explanation, or chain-of-thought. Output must start with [ and end with ]. Only JSON, nothing else."#,
            duration_minutes, library_summary, duration_minutes
        )
    }

    /// I5: Workout pacer — high-energy BPM-matched queue
    pub fn workout_pacer(
        library_summary: &str,
        duration_minutes: u32,
        intensity: &str,
    ) -> String {
        let energy_range = match intensity {
            "low" => "5-7",
            "high" => "8-10",
            _ => "6-9", // medium
        };

        format!(
            r#"You are a workout DJ creating a high-energy exercise playlist.

Target duration: ~{} minutes
Intensity: {} (energy range: {})

Available library tracks (id | title | artist | genre | mood | energy):
{}

Create a workout sequence that:
1. Starts with a warm-up track (slightly lower energy)
2. Hits peak energy for the main workout
3. Includes a cool-down track at the end
4. Prefers: fast tempo, energetic mood, genres like rock/metal/electronic/pop
5. Total ~{} minutes (estimate ~3.5 min per track)
6. ONLY use tracks with energy >= 5

Return ONLY a JSON array of track IDs in workout order:
["warmup-id", "peak-id", "peak-id", ..., "cooldown-id"]

IMPORTANT: Do NOT include any reasoning, thoughts, explanation, or chain-of-thought. Output must start with [ and end with ]. Only JSON, nothing else."#,
            duration_minutes, intensity, energy_range, library_summary, duration_minutes
        )
    }

    /// I6: Context-aware autoplay — time/day-based suggestions
    pub fn context_aware_autoplay(
        library_summary: &str,
        hour: u32,
        day_of_week: &str,
        recent_tracks: &str,
    ) -> String {
        let time_context = match hour {
            5..=8 => "Early morning - calm, gentle wake-up music",
            9..=11 => "Morning - upbeat, productive energy",
            12..=13 => "Lunchtime - relaxed, moderate energy",
            14..=16 => "Afternoon - focused, steady energy",
            17..=19 => "Evening - winding down, mixed energy",
            20..=22 => "Night - relaxed, ambient, or social depending on day",
            _ => "Late night - very calm, ambient, sleep-inducing",
        };

        let weekend_hint = match day_of_week {
            "Saturday" | "Sunday" => "\nIt's the weekend - user might want more relaxed or party vibes.",
            "Friday" => "\nIt's Friday evening - user might want upbeat/party music.",
            _ => "",
        };

        format!(
            r#"You are a context-aware music DJ. Suggest tracks based on the current time and context.

Current time: {}:00 ({})
Day: {}{}

Recently played (to avoid repeating):
{}

Available library tracks (id | title | artist | genre | mood | energy):
{}

Select 5-8 tracks that fit the current context:
- Match the time-of-day mood
- Consider the day (weekend vs weekday)
- Avoid recently played tracks
- Create a cohesive mini-session

Return ONLY a JSON array of track IDs:
["track-id-1", "track-id-2", ...]

IMPORTANT: Do NOT include any reasoning, thoughts, explanation, or chain-of-thought. Output must start with [ and end with ]. Only JSON, nothing else."#,
            hour, time_context, day_of_week, weekend_hint, recent_tracks, library_summary
        )
    }

    // ========================================================================
    // ANALYTICS & INSIGHTS PROMPTS (FAZA 6 - F1-F10)
    // ========================================================================

    /// F1: Listening profile — personal music taste narrative
    pub fn listening_profile(stats: &str) -> String {
        format!(
            r#"Ești un analist muzical prietenos. Generează un profil narativ de ascultare bazat pe statistici.

Statistici utilizator:
{}

Scrie un text narativ, conversațional (3-5 propoziții, în limba engleză), care descrie gustul muzical al utilizatorului:
- Ce genuri preferă
- Ce artiști ascultă cel mai mult
- Ce mood predomină
- Când ascultă cel mai mult
- O observație surprinzătoare sau interesantă

Returnează DOAR JSON:
{{ "profile_text": "Your listening personality: ...", "music_personality": "The Explorer" }}

music_personality = una din: "The Explorer", "The Loyalist", "The Mood Surfer", "The Energizer", "The Chill Seeker", "The Night Owl", "The Early Bird", "The Eclectic"
"#,
            stats
        )
    }

    /// F2: Weekly summary — digest of the week
    pub fn weekly_summary(stats: &str, top_tracks: &str) -> String {
        format!(
            r#"Generează un rezumat săptămânal al activității de ascultare.

Statistici (ultimele 7 zile):
{}

Top tracks săptămâna asta:
{}

Scrie un rezumat scurt (3-4 propoziții, în engleză) care include:
- Total tracks ascultate, timp total
- Top gen/artist al săptămânii
- O tendință interesantă
- O recomandare bazată pe ce a ascultat

Returnează DOAR JSON:
{{
  "summary_text": "This week you...",
  "highlight": "most played track or artist",
  "trend": "up/down/stable",
  "recommendation": "Based on your week, try..."
}}"#,
            stats, top_tracks
        )
    }

    /// F3: Time patterns — when does the user listen most
    pub fn time_patterns(hourly_data: &str) -> String {
        format!(
            r#"Analizează pattern-urile de ascultare în funcție de oră.

Date per oră (hora : nr ascultări):
{}

Identifică:
- Peak hours (orele cu cele mai multe ascultări)
- Quiet hours (orele cu puține/zero ascultări)
- Tiparul (morning person? night owl? all-day listener?)
- O observație interesantă

Returnează DOAR JSON:
{{
  "peak_hours": [20, 21, 22],
  "quiet_hours": [3, 4, 5],
  "pattern_name": "Night Owl",
  "insight": "You listen most between 8-11 PM..."
}}"#,
            hourly_data
        )
    }

    /// F6: Forgotten gems — rediscover old favorites
    pub fn forgotten_gems(tracks: &str) -> String {
        format!(
            r#"Primești o listă de track-uri care au fost ascultate dar uitate (neascultate de mult).

Track-uri uitate:
{}

Selectează cele mai interesante 5 track-uri pe care utilizatorul ar trebui să le re-descopere.
Pentru fiecare, scrie un motiv scurt de ce merită re-ascultat.

Returnează DOAR JSON:
{{
  "gems": [
    {{ "track_id": "id", "reason": "A classic you haven't played in weeks" }},
    ...
  ],
  "message": "We found some hidden gems in your library!"
}}"#,
            tracks
        )
    }

    /// G1: More like this — find similar tracks
    pub fn more_like_this(track_title: &str, track_artist: &str, library_summary: &str) -> String {
        format!(
            r#"Utilizatorul vrea track-uri similare cu: "{}" de {}

Tracks disponibile în librărie:
{}

Selectează 5-10 tracks din librărie care sunt similare ca:
- Gen muzical
- Mood/energie
- Stil artistic
- Eră/perioadă

Returnează DOAR un JSON array cu track IDs:
["track-id-1", "track-id-2", ...]"#,
            track_title, track_artist, library_summary
        )
    }

    /// G2: Artist deep dive — discover more about an artist
    pub fn artist_deep_dive(artist: &str) -> String {
        format!(
            r#"Ești un expert muzical. Fă un "deep dive" pe artistul: {}

Generează informații interesante:
1. Scurt background (1-2 propoziții)
2. 3 albume esențiale
3. 5 piese recomandate (titlu)
4. Artiști similari (3-5)
5. Un fun fact interesant

Returnează DOAR JSON:
{{
  "artist": "{}",
  "bio": "Short bio...",
  "essential_albums": ["Album 1", "Album 2", "Album 3"],
  "recommended_tracks": ["Song 1", "Song 2", "Song 3", "Song 4", "Song 5"],
  "similar_artists": ["Artist 1", "Artist 2", "Artist 3"],
  "fun_fact": "Did you know..."
}}"#,
            artist, artist
        )
    }

    /// G3: Genre explorer — discover a genre deeper
    pub fn genre_explorer(genre: &str) -> String {
        format!(
            r#"Ești un expert muzical. Explorează genul muzical: {}

Generează:
1. Scurtă descriere a genului (2-3 propoziții)
2. Sub-genuri principale (3-5)
3. Artiști legendari (5)
4. 5 piese esențiale (search queries)
5. Genuri înrudite (3)

Returnează DOAR JSON:
{{
  "genre": "{}",
  "description": "Genre description...",
  "sub_genres": ["Sub 1", "Sub 2"],
  "legendary_artists": ["Artist 1", "Artist 2"],
  "essential_tracks": ["Artist - Song", "Artist - Song"],
  "related_genres": ["Genre 1", "Genre 2"]
}}"#,
            genre, genre
        )
    }

    /// G5: Because you liked — recommendations from favorites
    pub fn because_you_liked(favorites_summary: &str) -> String {
        format!(
            r#"Bazat pe melodiile favorite ale utilizatorului, generează recomandări.

Favorite (titlu | artist | gen | mood):
{}

Generează 5-8 recomandări de noi piese de descoperit (NU din librărie).
Explică pe scurt de ce fiecare ar fi pe placul utilizatorului.

Returnează DOAR JSON:
{{
  "recommendations": [
    {{
      "title": "Song Title",
      "artist": "Artist",
      "search_query": "Artist - Song Title",
      "reason": "Because you like X, this has a similar vibe..."
    }}
  ],
  "insight": "Your taste leans towards..."
}}"#,
            favorites_summary
        )
    }

    /// G6: Surprise me — unexpected recommendation
    pub fn surprise_me(profile_summary: &str) -> String {
        format!(
            r#"Utilizatorul vrea o surpriză muzicală — ceva diferit de ce ascultă de obicei!

Profilul muzical curent:
{}

Generează 3-5 recomandări SURPRIZĂ care:
- Sunt din genuri pe care utilizatorul NU le ascultă frecvent
- Dar ar putea plăcea bazat pe alte aspecte ale profilului
- Sunt de calitate și apreciate critic

Returnează DOAR JSON:
{{
  "surprises": [
    {{
      "title": "Song Title",
      "artist": "Artist Name",
      "search_query": "Artist - Song Title",
      "genre": "Genre",
      "why_surprise": "This is different from your usual rock because..."
    }}
  ],
  "theme": "A catchy theme for this surprise set"
}}"#,
            profile_summary
        )
    }

    /// G8: Seasonal recommendations
    pub fn seasonal_recommendations(season: &str, preferences: &str) -> String {
        format!(
            r#"Generează recomandări muzicale sezoniere.

Sezonul: {}
Preferințe utilizator: {}

Generează 5-8 piese care se potrivesc perfect cu sezonul:
- Iarna: cozy, warm, holiday vibes
- Primăvara: fresh, uplifting, renewal
- Vara: energetic, fun, outdoor vibes
- Toamna: melancholic, nostalgic, warm

Returnează DOAR JSON:
{{
  "season": "{}",
  "mood": "seasonal mood description",
  "recommendations": [
    {{
      "title": "Song",
      "artist": "Artist",
      "search_query": "Artist - Song",
      "seasonal_fit": "Why this fits the season"
    }}
  ]
}}"#,
            season, preferences, season
        )
    }

    // ========================================================================
    // INSIGHTS EXTRAS (FAZA 6 — F8, F10)
    // ========================================================================

    /// F8: Mood timeline — analyze mood changes across listening history
    pub fn mood_timeline(history_with_moods: &str) -> String {
        format!(
            r#"You are a music psychologist AI. Analyze the user's mood evolution based on their listening history over time.

Listening history (chronological, with moods):
{}

Identify patterns, mood shifts, and emotional arcs across sessions.
Return JSON:
{{
  "timeline": [
    {{
      "period": "Morning / Week 1 / Monday",
      "dominant_mood": "energetic",
      "tracks_count": 5,
      "observation": "Started the day with high energy"
    }}
  ],
  "overall_pattern": "Description of the user's typical mood flow",
  "insights": ["Insight 1", "Insight 2"],
  "suggestion": "Based on your patterns, you might enjoy..."
}}"#,
            history_with_moods
        )
    }

    /// F10: Taste evolution — how music taste changed over months/years
    pub fn taste_evolution(monthly_stats: &str) -> String {
        format!(
            r#"You are a music analyst AI. Analyze how the user's music taste has evolved over time.

Monthly listening statistics:
{}

Identify trends, shifts in genre preferences, new discoveries, and how their taste matured.
Return JSON:
{{
  "evolution_phases": [
    {{
      "period": "Month/Year",
      "dominant_genres": ["genre1"],
      "new_discoveries": ["artist1"],
      "shift": "Description of what changed"
    }}
  ],
  "overall_trend": "How taste evolved overall",
  "current_phase": "Description of current musical identity",
  "prediction": "Where their taste might head next"
}}"#,
            monthly_stats
        )
    }

    // ========================================================================
    // HELP ASSISTANT (FAZA 7 — J4)
    // ========================================================================

    /// J4: Help assistant — answer questions about app features
    pub fn help_assistant(question: &str, available_features: &str) -> String {
        format!(
            r#"You are YTM-Free's help assistant. Answer the user's question about the app.

User question: "{}"

Available features:
{}

Provide a clear, concise answer. If the feature exists, explain how to use it.
If it doesn't exist, say so honestly.
Return JSON:
{{
  "answer": "Clear answer to the question",
  "related_features": ["Feature 1", "Feature 2"],
  "tip": "Optional pro tip"
}}"#,
            question, available_features
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_enhance_search_prompt() {
        let prompt = Prompts::enhance_search("muzică pentru relaxare", &["jazz".to_string()]);
        assert!(prompt.contains("muzică pentru relaxare"));
        assert!(prompt.contains("jazz"));
    }

    #[test]
    fn test_analyze_track_prompt() {
        let prompt = Prompts::analyze_track("Enter Sandman", "Metallica");
        assert!(prompt.contains("Enter Sandman"));
        assert!(prompt.contains("Metallica"));
    }
}

// ============================================================================
// FAZA 7 — LIBRARY CLEANUP PROMPTS (H1-H7)
// ============================================================================

impl Prompts {
    /// H1+H6: Detect duplicate/similar tracks
    pub fn detect_duplicates(track_pairs: &str) -> String {
        format!(
            r#"You are a music library deduplication expert.

Analyze these track pairs and identify duplicates or near-duplicates.
Consider: same song different recordings, live vs studio, remixes, spelling variations.

Track list:
{}

Return JSON:
{{
  "duplicates": [
    {{
      "track1": "exact title - artist as listed",
      "track2": "exact title - artist as listed",
      "similarity": "95",
      "suggestion": "Same song, different capitalization. Recommend keeping first one."
    }}
  ],
  "summary": "Found X duplicate groups in your library"
}}"#,
            track_pairs
        )
    }

    /// H3: Clean/fix messy metadata
    pub fn clean_metadata(tracks: &str) -> String {
        format!(
            r#"You are a music metadata cleanup expert.

Fix these track titles and artist names. Remove junk like:
- "(Official Video)", "(Audio)", "(Lyrics)", "[HD]", "(HQ)"
- Extra whitespace, weird characters
- "ft." / "feat." normalization
- Fix capitalization

Tracks:
{}

Return JSON:
{{
  "cleaned": [
    {{
      "original_title": "original title as listed",
      "original_artist": "original artist as listed",
      "clean_title": "Cleaned Title",
      "clean_artist": "Cleaned Artist",
      "changes": ["removed (Official Video)", "fixed capitalization"]
    }}
  ],
  "total_fixes": 5
}}"#,
            tracks
        )
    }

    /// H4: Normalize artist name variants
    pub fn normalize_artists(variants: &str) -> String {
        format!(
            r#"You are a music metadata expert.

These artist names might be variants of the same artist. Group them and pick the canonical (correct) name.
Only include groups where you find actual variants (more than one name mapping to the same artist).
Do NOT include artists that have no variants.

Artist names:
{}

Return JSON:
{{
  "groups": [
    {{
      "canonical": "AC/DC",
      "variants": ["ACDC", "Ac/Dc", "AC / DC"]
    }}
  ]
}}"#,
            variants
        )
    }

    /// H2: Auto-organize library into suggested playlists
    pub fn auto_organize(tracks_summary: &str) -> String {
        format!(
            r#"You are a music library organizer.

Based on these tracks and their metadata, suggest smart playlists to organize this library.
Group by mood, genre, energy, activity, or any creative theme you see.

Library summary:
{}

Return JSON:
{{
  "suggested_playlists": [
    {{
      "name": "Late Night Chill",
      "description": "Relaxing tracks perfect for winding down",
      "criteria": "mood: calm/relaxed, energy: 1-4",
      "estimated_tracks": 15
    }}
  ],
  "organization_score": 7,
  "tips": ["Your library is heavy on rock - consider adding variety"]
}}"#,
            tracks_summary
        )
    }

    /// H7: Suggest tracks to delete (never played, low quality matches)
    pub fn suggest_deletions(tracks: &str) -> String {
        format!(
            r#"You are a music library curator.

Review these tracks that have NEVER been played and suggest which ones might be safe to remove.
Consider: are they duplicates of played tracks? Are they from one-off imports? Do they fit the library's taste?

Never-played tracks:
{}

Return JSON:
{{
  "safe_to_delete": [
    {{
      "title": "track title",
      "artist": "artist name",
      "reason": "Duplicate of played version / Doesn't fit library taste / Import artifact"
    }}
  ],
  "keep": [
    {{
      "title": "track title",
      "artist": "artist name",
      "reason": "Fits your rock taste, just undiscovered"
    }}
  ],
  "summary": "Suggest removing X of Y never-played tracks"
}}"#,
            tracks
        )
    }

}

// ============================================================================
// FAZA 7 — AI CHAT PROMPTS (J1-J5)
// ============================================================================

impl Prompts {
    /// J1-J4: Chat system prompt with library context
    pub fn chat_system(library_summary: &str, current_track: &str) -> String {
        format!(
            r#"You are a friendly, knowledgeable music assistant for YTM-Free, a personal music player.
You speak naturally (in the user's language) and you're passionate about music.

You can help with:
- Music recommendations and discovery
- Artist/album/genre information and trivia
- Explaining song meanings, history, or cultural context
- Answering music theory questions
- Suggesting tracks based on mood or activity

User's library summary:
{}

Currently playing: {}

Keep responses concise but informative. Use emojis sparingly.
If asked about non-music topics, politely redirect to music.
Always be enthusiastic and engaging about music!"#,
            library_summary, current_track
        )
    }

    /// J2: Track trivia
    pub fn track_trivia(title: &str, artist: &str) -> String {
        format!(
            r#"Tell me interesting trivia and facts about the song "{}" by {}.

Return JSON:
{{
  "title": "{}",
  "artist": "{}",
  "facts": [
    "Interesting fact 1 about this song",
    "Interesting fact 2",
    "Interesting fact 3"
  ],
  "year": 1991,
  "album": "Album Name",
  "fun_fact": "The most surprising fact about this song"
}}"#,
            title, artist, title, artist
        )
    }

    /// J5: Music quiz question generator
    pub fn music_quiz(library_tracks: &str) -> String {
        format!(
            r#"Generate 5 fun music quiz questions based on the user's library.
Mix question types: guess the artist, guess the song, guess the year, true/false.
Be concise. Each question must have exactly 4 options.

User's tracks:
{}

Return JSON:
{{
  "questions": [
    {{
      "question": "The quiz question text",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correct": 1,
      "explanation": "Short reason why this answer is correct"
    }}
  ]
}}

IMPORTANT: "correct" must be the 0-based INDEX of the correct option (0, 1, 2, or 3). Return exactly 5 questions."#,
            library_tracks
        )
    }

    // ========================================================================
    // SOCIAL & SHARE (FAZA 8 — K1-K3)
    // ========================================================================

    /// K1: Generate shareable text for a track
    pub fn share_message(title: &str, artist: &str, mood: &str) -> String {
        format!(
            r#"Generate a short, catchy, shareable social media post about listening to a song.
Be creative, use 1-2 emojis, keep it under 200 characters.

Song: {} by {}
Current mood: {}

Return JSON:
{{
  "message": "The shareable text",
  "hashtags": ["tag1", "tag2"]
}}"#,
            title, artist, mood
        )
    }

    /// K2: Generate attractive playlist description
    pub fn playlist_description(track_list: &str) -> String {
        format!(
            r#"Generate an attractive, concise playlist description based on its tracks.
Capture the vibe, genres, and mood. Keep it 1-2 sentences, max 200 chars.

Tracks in playlist:
{}

Return JSON:
{{
  "description": "The playlist description",
  "vibe_tags": ["chill", "energetic"]
}}"#,
            track_list
        )
    }

    /// K3: Year in Review / Wrapped narrative
    pub fn year_in_review(annual_stats: &str) -> String {
        format!(
            r#"Generate a fun "Year in Review" music summary narrative, like Spotify Wrapped.
Be engaging, use emojis, highlight interesting patterns. Be concise.

User's annual stats:
{}

Return JSON:
{{
  "title": "Your 2025 Music Journey",
  "sections": [
    {{ "heading": "Section title", "text": "Narrative text with emojis" }}
  ],
  "fun_stats": ["Stat 1", "Stat 2", "Stat 3"],
  "music_personality": "A fun personality label"
}}"#,
            annual_stats
        )
    }

    // ========================================================================
    // UTILITIES (FAZA 8 — L1-L3)
    // ========================================================================

    /// L1: Explain an error in user-friendly language
    pub fn explain_error(error_message: &str) -> String {
        format!(
            r#"Explain this technical error in simple, user-friendly language.
Suggest what the user can do to fix it. Be concise, max 2 sentences.

Error: {}

Return JSON:
{{
  "explanation": "Simple explanation",
  "suggestion": "What to do"
}}"#,
            error_message
        )
    }

    /// L2: Settings advisor based on usage
    pub fn settings_advice(current_settings: &str, usage_stats: &str) -> String {
        format!(
            r#"Analyze the user's current settings and usage stats. Suggest optimizations.
Be practical and concise. Max 5 suggestions.

Current settings:
{}

Usage stats:
{}

Return JSON:
{{
  "suggestions": [
    {{ "setting": "setting_name", "current": "current value", "recommended": "new value", "reason": "why" }}
  ],
  "overall_score": 8,
  "summary": "Brief overall assessment"
}}"#,
            current_settings, usage_stats
        )
    }

    /// L3: Storage analysis
    pub fn storage_analysis(storage_info: &str) -> String {
        format!(
            r#"Analyze the user's music storage usage. Identify potential space savings.
Be concise and practical.

Storage info:
{}

Return JSON:
{{
  "total_size_mb": 500,
  "tracks_analyzed": 100,
  "suggestions": [
    {{ "action": "what to do", "savings_mb": 50, "affected_tracks": 5 }}
  ],
  "summary": "Brief assessment"
}}"#,
            storage_info
        )
    }

    /// AI DJ Mode: Generate radio-style commentary between tracks
    pub fn dj_commentary(
        prev_title: &str,
        prev_artist: &str,
        prev_genre: Option<&str>,
        prev_mood: Option<&str>,
        next_title: &str,
        next_artist: &str,
        next_genre: Option<&str>,
        next_mood: Option<&str>,
        style: &str,
        language: &str,
    ) -> String {
        let prev_genre_str = prev_genre.unwrap_or("unknown");
        let prev_mood_str = prev_mood.unwrap_or("unknown");
        let next_genre_str = next_genre.unwrap_or("unknown");
        let next_mood_str = next_mood.unwrap_or("unknown");

        format!(
            r#"You are an AI radio DJ. Generate a SHORT spoken commentary to transition between two songs.
Keep it natural, engaging, and under 2-3 sentences. Match the DJ style specified.

Previous track: "{}" by {} (genre: {}, mood: {})
Next track: "{}" by {} (genre: {}, mood: {})

DJ Style: {}
Language: {}

Style guide:
- "classic_fm": Professional, warm, knowledgeable. Mention interesting facts.
- "hype": High energy, excited, uses exclamations. Build anticipation.
- "chill": Laid back, smooth, poetic. Create a relaxing vibe.
- "fun": Humorous, playful, might make puns or jokes.
- "storyteller": Connect the songs through a narrative or historical angle.

Return JSON:
{{{{
  "commentary": "The actual DJ commentary text to be spoken aloud",
  "transition_type": "smooth|energy_shift|genre_bridge|surprise",
  "energy": "low|medium|high"
}}}}

IMPORTANT: The commentary should sound like a real radio DJ speaking naturally. Never mention JSON, AI, or technical terms."#,
            prev_title, prev_artist, prev_genre_str, prev_mood_str,
            next_title, next_artist, next_genre_str, next_mood_str,
            style, language
        )
    }

    // ============================================================================
    // FAZA 11: AI DJ TRIGGER PROMPTS
    // ============================================================================

    /// DJ TrackStart: Intro at track beginning (10% chance)
    pub fn dj_track_start(
        title: &str,
        artist: &str,
        genre: Option<&str>,
        mood: Option<&str>,
        style: &str,
        language: &str,
    ) -> String {
        let genre_str = genre.unwrap_or("unknown");
        let mood_str = mood.unwrap_or("unknown");

        format!(
            r#"You are an AI radio DJ with a {} style. Generate a SHORT (1-2 sentence) introduction for the track that's starting now.
Do NOT describe the song in detail. Just a quick, natural-sounding intro.

Track: "{}" by {}
Genre: {}
Mood: {}

Language: {}

Return JSON:
{{
  "commentary": "The DJ intro text (max 2 sentences)",
  "transition_type": "track_intro",
  "energy": "medium"
}}"#,
            style, title, artist, genre_str, mood_str, language
        )
    }

    /// DJ QueueEmpty: Farewell when playlist ends
    pub fn dj_queue_empty(
        title: &str,
        artist: &str,
        style: &str,
        language: &str,
    ) -> String {
        format!(
            r#"You are an AI radio DJ with a {} style. Generate a farewell message when the queue is empty.
Keep it warm and concise (1-2 sentences).

Last track: "{}" by {}

Language: {}

Return JSON:
{{
  "commentary": "The farewell message (max 2 sentences)",
  "transition_type": "goodbye",
  "energy": "low"
}}"#,
            style, title, artist, language
        )
    }

    /// DJ LongSession: Check-in after 30+ minutes
    pub fn dj_long_session(
        duration_minutes: u32,
        tracks_count: u32,
        style: &str,
        language: &str,
    ) -> String {
        format!(
            r#"You are an AI radio DJ with a {} style. Generate a message for when the listener has been listening for 30+ minutes.
Acknowledge the session duration and encourage them.

Session: {} minutes, {} tracks played

Language: {}

Return JSON:
{{
  "commentary": "The session check-in message (max 2 sentences)",
  "transition_type": "check_in",
  "energy": "medium"
}}"#,
            style, duration_minutes, tracks_count, language
        )
    }

    /// DJ FirstTrackOfDay: Time-aware greeting
    pub fn dj_first_track_of_day(
        title: &str,
        artist: &str,
        hour: u8,
        time_of_day: &str,
        style: &str,
        language: &str,
    ) -> String {
        format!(
            r#"You are an AI radio DJ with a {} style. Generate a time-aware greeting for the first track of the day.
Time of day: {} (hour: {})

Last track: "{}" by {}

Language: {}

Return JSON:
{{
  "commentary": "The time-aware greeting (max 2 sentences)",
  "transition_type": "greeting",
  "energy": "medium"
}}"#,
            style, time_of_day, hour, title, artist, language
        )
    }

    /// DJ Milestone: Celebration at 50/100/500/1000+ tracks
    pub fn dj_milestone(
        milestone_type: &str,
        count: u32,
        title: &str,
        artist: &str,
        style: &str,
        language: &str,
    ) -> String {
        format!(
            r#"You are an AI radio DJ with a {} style. Generate a celebratory message for reaching a milestone.
Milestone: {} (total tracks: {})

Current track: "{}" by {}

Language: {}

Return JSON:
{{
  "commentary": "The milestone celebration message (max 2 sentences)",
  "transition_type": "celebration",
  "energy": "high"
}}"#,
            style, milestone_type, count, title, artist, language
        )
    }

    /// DJ TimeAnnouncement: Radio-style time check
    pub fn dj_time_announcement(
        hour: u8,
        minute: u8,
        title: &str,
        artist: &str,
        style: &str,
        language: &str,
    ) -> String {
        format!(
            r#"You are an AI radio DJ with a {} style. Generate a radio-style time announcement.
Time: {:02}:{:02}
Current track: "{}" by {}

Only announce at 9am, 12pm, 3pm, 6pm, 9pm.
Keep it brief - just the time and a smooth transition.

Language: {}

Return JSON:
{{
  "commentary": "The time announcement (max 2 sentences)",
  "transition_type": "time_check",
  "energy": "medium"
}}"#,
            style, hour, minute, title, artist, language
        )
    }

    /// DJ MoodShift: Commentary on genre/mood transitions
    pub fn dj_mood_shift(
        prev: &str,
        current: &str,
        prev_title: &str,
        next_title: &str,
        style: &str,
        language: &str,
    ) -> String {
        format!(
            r#"You are an AI radio DJ with a {} style. Generate commentary when the mood/genre shifts.
Previous mood: {}
Current mood: {}

Previous track: "{}"
Next track: "{}"

Language: {}

Return JSON:
{{
  "commentary": "The mood shift commentary (max 2 sentences)",
  "transition_type": "mood_bridge",
  "energy": "medium"
}}"#,
            style, prev, current, prev_title, next_title, language
        )
    }

    /// DJ UserRequest: On-demand commentary (user clicked 📻 button)
    pub fn dj_user_request(
        title: &str,
        artist: &str,
        genre: Option<&str>,
        mood: Option<&str>,
        _next_genre: Option<&str>,
        style: &str,
        language: &str,
    ) -> String {
        let genre_str = genre.unwrap_or("unknown");
        let mood_str = mood.unwrap_or("unknown");

        format!(
            r#"You are an AI radio DJ with a {} style. Generate a general music commentary at the user's request.
The user clicked the 📻 button to hear something.

Track: "{}" by {}
Genre: {}
Mood: {}

Language: {}

Return JSON:
{{
  "commentary": "The DJ commentary (max 2 sentences)",
  "transition_type": "user_request",
  "energy": "medium"
}}"#,
            style, title, artist, genre_str, mood_str, language
        )
    }
}
